services:
  mongodb:
    image: mongo:8.0
    command: ['mongod', '--replSet', 'rs0', '--bind_ip_all']
    ports:
      - '127.0.0.1:27017:27017'
    volumes:
      - mongodb:/data/db
    healthcheck:
      test: ['CMD', 'mongosh', '--quiet', '--eval', 'db.adminCommand({ping:1}).ok']
      interval: 2s
      timeout: 5s
      retries: 30

volumes:
  mongodb:
